### ISSUE TITLE
Class and Methods - Issue

### ISSUE THREAD

**Issue by rootanand** [Ashiq-jr/BillingSystem-2.0#7]
Dont add the products collection and the methods to add, remove and edit products into the product class. 
Same for other classes.
Remember that a product is just a single item and it must have methods concerning that alone. Not the collection. 
You can create a class called ProductsRepository to have those method. Repository is the usual class that contains the methods to handle DB or  File actions.

**Comment by Ashiq-jr** [comment]
Created a Separate Repository Class Where ever Needed and shifted the Collections and Methods There.  used inheritance to inherit the Properties of the Parent class to the Repository class.

**Comment by rootanand** [comment]
Should not inherit. Instead use a collection of the product class inside
the products repo and add remove and edit contents of that collection.
Inheritance is not applicable in that scenario.

**Comment by Ashiq-jr** [comment]
I have used Collections only sir. i only inherited fields from product class like id,name,category,etc. or should i just create object of the product class inside productRepository class to work with.

**Comment by Ashiq-jr** [comment]
Thank you sir. Removed the UnWanted use of Inheritance From Repository classes.
